// Generated by scripts/type-casts.sh; do not edit.
package gobject

import "base:intrinsics"
import glib "glib:glib"

OBJECT :: #force_inline proc "contextless" (ptr: $Ptr) -> ^Object where intrinsics.type_is_pointer(Ptr) {
    return type_cast(Object, ptr, object_get_type)
}

IS_OBJECT :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, object_get_type)
}

INITIALLY_UNOWNED :: #force_inline proc "contextless" (ptr: $Ptr) -> ^InitiallyUnowned where intrinsics.type_is_pointer(Ptr) {
    return type_cast(InitiallyUnowned, ptr, initially_unowned_get_type)
}

IS_INITIALLY_UNOWNED :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, initially_unowned_get_type)
}

BINDING :: #force_inline proc "contextless" (ptr: $Ptr) -> ^Binding where intrinsics.type_is_pointer(Ptr) {
    return type_cast(Binding, ptr, binding_get_type)
}

IS_BINDING :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, binding_get_type)
}

BINDING_GROUP :: #force_inline proc "contextless" (ptr: $Ptr) -> ^BindingGroup where intrinsics.type_is_pointer(Ptr) {
    return type_cast(BindingGroup, ptr, binding_group_get_type)
}

IS_BINDING_GROUP :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, binding_group_get_type)
}

SIGNAL_GROUP :: #force_inline proc "contextless" (ptr: $Ptr) -> ^SignalGroup where intrinsics.type_is_pointer(Ptr) {
    return type_cast(SignalGroup, ptr, signal_group_get_type)
}

IS_SIGNAL_GROUP :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, signal_group_get_type)
}

TYPE_MODULE :: #force_inline proc "contextless" (ptr: $Ptr) -> ^TypeModule where intrinsics.type_is_pointer(Ptr) {
    return type_cast(TypeModule, ptr, type_module_get_type)
}

IS_TYPE_MODULE :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, type_module_get_type)
}

TYPE_PLUGIN :: #force_inline proc "contextless" (ptr: $Ptr) -> ^TypePlugin where intrinsics.type_is_pointer(Ptr) {
    return type_cast(TypePlugin, ptr, type_plugin_get_type)
}

IS_TYPE_PLUGIN :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {
    return type_is(ptr, type_plugin_get_type)
}

