#!/usr/bin/env bash
# Writes gio/type_casts.odin: for each TYPE_FOO :: foo_get_type in gio/gio.odin, a FOO cast
# and an IS_FOO check, as GIO's C macros do. Also writes gobject/type_casts.odin: the same for
# the GObject classes in the list below. Run by scripts/generate.sh after postprocess.
# shellcheck disable=SC2016,SC2094  # the Odin text has literal $; gio.odin is only read here
set -euo pipefail

cd "$(dirname "$0")/.."
src=gio/gio.odin
out=gio/type_casts.odin

{
    printf '%s\n' '// Generated by scripts/type-casts.sh from gio.odin; do not edit.' \
        'package gio' '' \
        'import "base:intrinsics"' \
        'import glib "glib:glib"' \
        'import gobj "glib:gobject"' '' \
        '// The casts below are polymorphic, so Odin does not count their body as a use of gobj.' \
        '@(private = "file")' \
        'Type :: gobj.Type' ''
    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^TYPE_([A-Z0-9_]+)[[:space:]]*::[[:space:]]*(.+)_get_type[[:space:]]*$ ]]; then
            upper=${BASH_REMATCH[1]}
            snake=${BASH_REMATCH[2]}
            # An error domain has a quark, not a class.
            if grep -q "${snake}_quark" "$src"; then continue; fi
            pascal=$(echo "$snake" | sed -r 's/(^|_)([a-z])/\U\2/g')
            case "$pascal" in
            *Dbus*) pascal=${pascal//Dbus/DBus} ;;
            *[a-z]Fd[A-Z]*) pascal=$(echo "$pascal" | sed -r 's#(.*)Fd(.*)#\1FD\2#') ;;
            *Io*) pascal=${pascal//Io/IO} ;;
            *Ip*) pascal=${pascal//Ip/IP} ;;
            esac
            printf '%s :: #force_inline proc "contextless" (ptr: $Ptr) -> ^%s where intrinsics.type_is_pointer(Ptr) {\n' "$upper" "$pascal"
            printf '    return gobj.type_cast(%s, ptr, TYPE_%s)\n}\n\n' "$pascal" "$upper"
            printf 'IS_%s :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {\n' "$upper"
            printf '    return gobj.type_is(ptr, TYPE_%s)\n}\n\n' "$upper"
        fi
    done <"$src"
} >"$out"

# gobject: most TYPE_FOO in gobject.odin are boxed types or enums, which the header does not
# tell from classes, so the classes are listed (DECISIONS §11). TYPE_OBJECT is a constant, not
# a procedure, so OBJECT checks against object_get_type.
out=gobject/type_casts.odin
{
    printf '%s\n' '// Generated by scripts/type-casts.sh; do not edit.' \
        'package gobject' '' \
        'import "base:intrinsics"' \
        'import glib "glib:glib"' ''
    for entry in OBJECT:Object:object_get_type INITIALLY_UNOWNED:InitiallyUnowned:initially_unowned_get_type \
        BINDING:Binding:binding_get_type BINDING_GROUP:BindingGroup:binding_group_get_type \
        SIGNAL_GROUP:SignalGroup:signal_group_get_type TYPE_MODULE:TypeModule:type_module_get_type \
        TYPE_PLUGIN:TypePlugin:type_plugin_get_type; do
        IFS=: read -r upper pascal getter <<<"$entry"
        grep -q "^$pascal :: " gobject/gobject.odin || { echo "type-casts: gobject has no $pascal" >&2; exit 1; }
        printf '%s :: #force_inline proc "contextless" (ptr: $Ptr) -> ^%s where intrinsics.type_is_pointer(Ptr) {\n' "$upper" "$pascal"
        printf '    return type_cast(%s, ptr, %s)\n}\n\n' "$pascal" "$getter"
        printf 'IS_%s :: #force_inline proc "contextless" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {\n' "$upper"
        printf '    return type_is(ptr, %s)\n}\n\n' "$getter"
    done
} >"$out"
